name: Infra Construction

on:
  workflow_dispatch:

jobs:
  DeployInfraAndBuild:
    name: Deploy Infra and Build
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Cache Terraform binary
        uses: actions/cache@v3
        with:
          path: /usr/bin/terraform
          key: terraform-cache-${{ runner.os }}-${{ hashFiles('**/terraform') }}
          restore-keys: |
            terraform-cache-${{ runner.os }}-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
     
      - name: Update Terraform Setup
        working-directory: Terraform 
        run: |
           sed -i "s|{tmp_subscription_id}|${{ secrets.SUBSCRIPTION_ID }}|g" variables.tfvars
           sed -i "s|{tmp_tenant_id}|${{ secrets.TENANT_ID }}|g" variables.tfvars
           sed -i "s|{tmp_sp_client_id}|${{ secrets.SP_CLIENT_ID }}|g" variables.tfvars
           sed -i "s|{tmp_sp_client_secret}|${{ secrets.SP_CLIENT_SECRET }}|g" variables.tfvars

           sed -i "s|{tmp_resource_group_name}|${{ vars.RESOURCE_GROUP_NAME }}|g" variables.tfvars
           sed -i "s|{tmp_resource_group_location}|${{ vars.RESOURCE_GROUP_LOCATION }}|g" variables.tfvars

           sed -i "s|{tmp_db_server_name}|${{ vars.DB_SERVER_NAME }}|g" variables.tfvars
           sed -i "s|{tmp_db_server_user}|${{ secrets.DB_SERVER_USER }}|g" variables.tfvars
           sed -i "s|{tmp_db_server_password}|${{ secrets.DB_SERVER_PASSWORD }}|g" variables.tfvars

           sed -i "s|{tmp_db_name}|${{ vars.DB_NAME }}|g" variables.tfvars
           
           sed -i "s|{tmp_app_name}|${{ vars.APP_NAME }}|g" variables.tfvars

      - name: Start Terraform Deploy
        working-directory: Terraform
        run: |
          terraform init
          terraform validate
          terraform plan -var-file=variables.tfvars
          terraform apply -auto-approve -var-file=variables.tfvars

  RestoreDataToDB:
    name: Restore Data to Postgres DB
    #needs: DeployInfraAndBuild
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Psql
        run: |
          sudo apt update
          sudo apt install postgresql-client
          pg_restore --version

      - name: Start Restore Data
        working-directory: data
        env:
          PGPASSWORD: ${{ secrets.DB_SERVER_PASSWORD }}
          PGSSLMODE: require
        run: |
          pg_restore -U ${{ secrets.DB_SERVER_USER }}@${{ vars.DB_SERVER_NAME }} -h ${{ vars.DB_SERVER_NAME }}.postgres.database.azure.com -p 5432 -d ${{ vars.DB_NAME }} --clean --no-owner ./techconfdb_backup.tar
